---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  source:
    path: argo-apps/tools/dev/gitops-controller
    repoURL: "https://github.com/stefanG41/argocd-gitops.git"
    targetRevision: master
    directory:
      recurse: false
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: false
      prune: false
  project: default
---
