---
apiVersion: v1
data:
  use-proxy-protocol: "false"
kind: ConfigMap
metadata:
  name: argocd-ingress-ingress-nginx-controller
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
---
